services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitterdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/twitterdb
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm start"


volumes:
  pgdata:
